# Generated by Django 4.1.4 on 2023-01-06 07:56

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(default='Somewhere', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(upload_to='static/profiles'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
